In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [5]:
fake = pd.read_csv('/content/fake.csv', on_bad_lines='skip', engine='python')
true = pd.read_csv('/content/true.csv')

In [6]:
fake["label"] = 0
true["label"] = 1

In [7]:
data = pd.concat([fake, true], axis=0)

data = data.sample(frac=1).reset_index(drop=True)

data.head()

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,label
0,"Turkey urges Iraqi Kurds to drop referendum, c...",ISTANBUL (Reuters) - Turkey appealed to northe...,worldnews,"September 22, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,ISLAMIC JUSTICE: Britain Is Stunned When They ...,"Like dominoes, the Hijra keeps marching across...",left-news,"May 9, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Erdogan critic held in Spain returns to German...,"DUESSELDORF, Germany (Reuters) - Author Dogan ...",worldnews,"October 19, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,Kenya's nurses call off their strike as lectur...,NAIROBI (Reuters) - Nurses in Kenya have ended...,worldnews,"November 2, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,VIRAL VIDEO: A Must Watch Video Hillary Doesn’...,,politics,"Oct 22, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38552 entries, 0 to 38551
Columns: 173 entries, title to label
dtypes: float64(43), int64(1), object(129)
memory usage: 50.9+ MB

In [9]:
data.isnull().sum()

title               0
text                1
subject             5
date                5
Unnamed: 4      38548
                ...
Unnamed: 168    38552
Unnamed: 169    38552
Unnamed: 170    38552
Unnamed: 171    38552
label               0
Length: 173, dtype: int64

In [10]:
data['label'].value_counts()

label
1    19569
0    18983
Name: count, dtype: int64

In [11]:
data = data[['text','label']]

In [12]:
X = data['text']

y = data['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [14]:
vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

X_train = X_train.fillna('')
X_test = X_test.fillna('')

X_train = vectorizer.fit_transform(X_train)

X_test = vectorizer.transform(X_test)

In [15]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [16]:
prediction = model.predict(X_test)

In [17]:
accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 0.9836597069122034

In [18]:
cm = confusion_matrix(y_test, prediction)

print(cm)

[[3723   73]
 [  53 3862]]

In [19]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      3796
           1       0.98      0.99      0.98      3915

    accuracy                           0.98      7711
   macro avg       0.98      0.98      0.98      7711
weighted avg       0.98      0.98      0.98      7711

In [20]:
news = [
    "NASA confirms Earth will have two moons next week."
]

news_vector = vectorizer.transform(news)

result = model.predict(news_vector)

if result[0] == 1:
    print("Real News")
else:
    print("Fake News")

Fake News

In [22]:
news = [
    "The government announced a new education policy today."
]
news_vector = vectorizer.transform(news)

result = model.predict(news_vector)

if result[0] == 1:
    print("Real News")
else:
    print("Fake News")

Fake News